const $ = id => document.getElementById(id);
const launchButton = $('launch'); const versionSelect = $('version'); const minecraftVersionPicker = $('minecraft-version-picker'); const activeProfileInput = $('active-profile'); const activeProfilePicker = $('active-profile-picker'); const profileSourceInput = $('profile-source'); const profileSourcePicker = $('profile-source-picker'); const profileCreateVersion = $('profile-create-version'); const profileCreateVersionPicker = $('profile-create-version-picker'); const profileName = $('profile-name'); const avatar = $('avatar'); const status = $('status'); const progressWrap = $('progress-wrap'); const progressBar = $('progress-bar'); const progressLabel = $('progress-label'); const progressPercent = $('progress-percent');
const modSearch = $('mod-search'); const modQuery = $('mod-query'); const modStatus = $('mod-status'); const modResults = $('mod-results'); const featuredSections = $('featured-sections'); const recommendations = $('recommendations'); const searchSection = $('search-section'); const installFpsPack = $('install-fps-pack');
const libraryView = $('library-view'); const profilesView = $('profiles-view'); const settingsView = $('settings-view'); const editorView = $('editor-view'); const editorName = $('editor-name'); const editorMeta = $('editor-meta'); const editorVersion = $('editor-version'); const editorPlay = $('editor-play'); const editorUpdate = $('editor-update'); const editorAutosync = $('editor-autosync'); const editorStatus = $('editor-status'); const editorInstalledStatus = $('editor-installed-status'); const editorInstalled = $('editor-installed'); const editorRecommended = $('editor-recommended'); const editorResults = $('editor-results'); const editorSearch = $('editor-mod-search'); const editorQuery = $('editor-query'); const openLibrary = $('open-library'); const homeBrand = $('home-brand'); const heroProfiles = $('hero-profiles'); const heroMods = $('hero-mods'); const quickNewProfile = $('quick-new-profile'); const openProfiles = $('open-profiles'); const openSettings = $('open-settings'); const clearSearch = $('clear-search'); const openImport = $('open-import'); const focusNewProfile = $('focus-new-profile'); const importArea = $('import-area'); const profileSearch = $('profile-search'); const profileCount = $('profile-count'); const activeVersionBadge = $('active-version-badge'); const libraryVersion = $('library-version');
const createProfile = $('create-profile'); const profileNameInput = $('profile-name-input'); const importProfile = $('import-profile'); const importProfileCode = $('import-profile-code'); const profilesStatus = $('profiles-status'); const profilesList = $('profiles-list');
const autoUpdate = $('auto-update'); const beginnerMode = $('beginner-mode'); const experimentalVersions = $('experimental-versions'); const reducedMotion = $('reduced-motion'); const readableFont = $('readable-font'); const uiScale = $('ui-scale'); const backupRetention = $('backup-retention'); const settingsVersion = $('settings-version'); const settingsVersionPicker = $('settings-version-picker'); const fabricLoader = $('fabric-loader'); const fabricLoaderPicker = $('fabric-loader-picker'); const settingsStatus = $('settings-status'); const saveSettings = $('save-settings');
const toastView = $('toast');
let profile = null; let displayedProgress = 0; let targetProgress = 0; let progressFrame; let recommendedProjects = []; let recommendedProjectIds = new Set(); let installedProjectIds = new Set(); let supportedVersions = []; let activeModProfile = null; let editingProfile = null; let profileFilter = 'all';

function setStatus(message) { status.textContent = message; }
function friendlyError(error) { const raw = String(error?.message || error || 'Something went wrong.').replace(/^Error invoking remote method '[^']+': Error:\s*/i, ''); if (/ENOSPC/i.test(raw)) return 'There is not enough disk space. Free some space and try again.'; if (/ECONN|timed out|network|fetch/i.test(raw)) return 'Swirl could not reach the download service. Check your connection and try again.'; if (/EADDRINUSE/i.test(raw)) return 'That network port is already being used. Choose another port.'; return raw; }
function notify(message, kind = 'info') { toastView.textContent = message; toastView.dataset.kind = kind; toastView.hidden = false; clearTimeout(notify.timer); notify.timer = setTimeout(() => { toastView.hidden = true; }, 3500); }
function setBusy(busy, text) { launchButton.disabled = busy; launchButton.querySelector('span').textContent = text; }
function updateProfile(account) { profile = account || null; profileName.textContent = account ? account.username : 'Choose a name'; avatar.textContent = account ? account.username.slice(0, 2).toUpperCase() : 'SW'; setStatus(account ? 'Ready.' : 'Choose a player name.'); }
function animateProgress() { const difference = targetProgress - displayedProgress; displayedProgress = Math.abs(difference) < 0.15 ? targetProgress : displayedProgress + difference * 0.12; progressBar.style.width = `${displayedProgress}%`; progressPercent.textContent = `${Math.round(displayedProgress)}%`; if (displayedProgress !== targetProgress) progressFrame = requestAnimationFrame(animateProgress); else progressFrame = undefined; }
function setProgressTarget(percent) { targetProgress = Math.max(targetProgress, Math.min(100, percent)); if (!progressFrame) progressFrame = requestAnimationFrame(animateProgress); }
function formatDownloads(value) { return new Intl.NumberFormat().format(value || 0); }
function clear(element) { element.replaceChildren(); }
function applyAccessibility(settings) { document.documentElement.classList.toggle('reduce-motion', settings.reducedMotion === true); document.documentElement.classList.toggle('readable-font', settings.readableFont === true); window.icecream.setUiScale(Number(settings.uiScale) || 1).catch(() => {}); }
function formatBytes(bytes) { const value = Number(bytes) || 0; if (value < 1024) return `${value} B`; if (value < 1024 ** 2) return `${(value / 1024).toFixed(1)} KB`; if (value < 1024 ** 3) return `${(value / 1024 ** 2).toFixed(1)} MB`; return `${(value / 1024 ** 3).toFixed(1)} GB`; }
function createCustomPicker(container, valueHolder, options, selectedValue) {
  clear(container); valueHolder.value = selectedValue === undefined || selectedValue === null ? (options[0]?.value || '') : selectedValue; const trigger = document.createElement('button'); trigger.type = 'button'; trigger.className = 'picker-trigger'; trigger.setAttribute('aria-haspopup', 'listbox'); trigger.setAttribute('aria-expanded', 'false'); const label = document.createElement('span'); const caret = document.createElement('span'); caret.className = 'picker-caret'; caret.textContent = 'v'; trigger.append(label, caret); const list = document.createElement('div'); list.className = 'picker-list'; list.role = 'listbox'; list.hidden = true;
  const refresh = () => { const selected = options.find(option => option.value === valueHolder.value); label.textContent = selected?.label || 'Choose a version'; };
  for (const data of options) { const option = document.createElement('button'); option.type = 'button'; option.className = 'picker-option'; option.role = 'option'; option.dataset.value = data.value; option.textContent = data.label; if (data.value === valueHolder.value) { option.classList.add('selected'); option.setAttribute('aria-selected', 'true'); } option.addEventListener('click', () => { valueHolder.value = data.value; list.querySelectorAll('.picker-option').forEach(item => { item.classList.toggle('selected', item.dataset.value === data.value); item.setAttribute('aria-selected', String(item.dataset.value === data.value)); }); refresh(); list.hidden = true; trigger.setAttribute('aria-expanded', 'false'); container.classList.remove('open'); container.dispatchEvent(new Event('icecream-change')); }); list.append(option); }
  const close = () => { list.hidden = true; trigger.setAttribute('aria-expanded', 'false'); container.classList.remove('open'); };
  trigger.addEventListener('click', () => { const opening = list.hidden; document.querySelectorAll('.custom-picker.open').forEach(picker => { picker.classList.remove('open'); const other = picker.querySelector('.picker-list'); const otherTrigger = picker.querySelector('.picker-trigger'); if (other) other.hidden = true; if (otherTrigger) otherTrigger.setAttribute('aria-expanded', 'false'); }); list.hidden = !opening; trigger.setAttribute('aria-expanded', String(opening)); container.classList.toggle('open', opening); if (opening) (list.querySelector('.selected') || list.firstElementChild)?.focus(); });
  container.addEventListener('keydown', event => { const items = [...list.querySelectorAll('.picker-option')]; const current = items.indexOf(document.activeElement); if (event.key === 'Escape') { close(); trigger.focus(); } else if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); if (list.hidden) trigger.click(); else items[(current + (event.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length]?.focus(); } else if (event.key === 'Home') { event.preventDefault(); items[0]?.focus(); } else if (event.key === 'End') { event.preventDefault(); items.at(-1)?.focus(); } }); container.append(trigger, list); refresh();
}
window.swirlCreatePicker = createCustomPicker;
function setActiveTab(view) { const active = view === 'editor' ? 'profiles' : view === 'hosts' ? 'host' : view; const tabs = { library: openLibrary, profiles: openProfiles, host: $('open-hosts'), settings: openSettings }; Object.entries(tabs).forEach(([name, button]) => { const selected = name === active; button.classList.toggle('active', selected); if (selected) button.setAttribute('aria-current', 'page'); else button.removeAttribute('aria-current'); }); }
window.swirlSetActiveTab = setActiveTab;
function showView(view) { libraryView.hidden = view !== 'library'; profilesView.hidden = view !== 'profiles'; settingsView.hidden = view !== 'settings'; editorView.hidden = view !== 'editor'; const hostPage = $('hosts-view'); if (hostPage) hostPage.hidden = true; setActiveTab(view); if (view === 'profiles') { loadProfiles(); loadProfileSourcePicker(); loadProfileCreationVersionPicker(); } if (view === 'settings') loadSettings(); if (view === 'editor') loadProfileEditor(); }
function versionOptions() { return supportedVersions.map(version => ({ value: version.id, label: `${version.id}${version.experimental ? ' - test' : ''}` })); }
function loadVersionPicker() { createCustomPicker(minecraftVersionPicker, versionSelect, versionOptions(), versionSelect.value || supportedVersions[0]?.id || '26.2'); }
function loadProfileCreationVersionPicker() { const desired = profileCreateVersion.value || versionSelect.value || supportedVersions[0]?.id || '26.2'; createCustomPicker(profileCreateVersionPicker, profileCreateVersion, versionOptions(), desired); }
async function persistActiveProfile(profileId = activeProfileInput.value) { const settings = await window.icecream.settings(); const activeProfiles = { ...(settings.activeProfiles || {}), [versionSelect.value]: profileId || '' }; await window.icecream.saveSettings({ activeProfiles }); }
async function loadActiveProfilePicker() { const [profiles, settings] = await Promise.all([window.icecream.modProfiles(), window.icecream.settings()]); const compatible = profiles.filter(item => item.gameVersion === versionSelect.value); const options = [{ value: '', label: compatible.length ? 'Choose a profile' : 'Create a profile' }, ...compatible.map(item => ({ value: item.id, label: `${item.name}${item.autoSync ? ' - auto-update' : ''}` }))]; const saved = settings.activeProfiles?.[versionSelect.value] || ''; const preferred = compatible.some(item => item.id === activeProfileInput.value) ? activeProfileInput.value : compatible.some(item => item.id === saved) ? saved : ''; createCustomPicker(activeProfilePicker, activeProfileInput, options, preferred); activeModProfile = compatible.find(item => item.id === activeProfileInput.value) || null; }
async function loadProfileSourcePicker() { const profiles = await window.icecream.modProfiles(); const options = [{ value: '', label: 'Start empty' }, ...profiles.map(item => ({ value: item.id, label: `${item.name} - ${item.gameVersion}` }))]; const preferred = options.some(item => item.value === profileSourceInput.value) ? profileSourceInput.value : ''; createCustomPicker(profileSourcePicker, profileSourceInput, options, preferred); }
async function refreshInstalledIndex() { installedProjectIds = activeModProfile ? new Set((await window.icecream.installedMods(versionSelect.value, activeModProfile.id)).map(mod => mod.projectId)) : new Set(); }
function reflectInstalled(projectId) { document.querySelectorAll(`[data-project-id="${projectId}"]`).forEach(button => { button.textContent = 'Installed'; }); }
async function installProjects(projects, button, label) { if (!activeModProfile) { setStatus('Choose a profile before adding mods.'); showView('profiles'); return; } button.disabled = true; const original = button.textContent; button.textContent = label; try { const installed = []; for (const item of projects) installed.push(...(item.versionId ? await window.icecream.installModVersion(item.id, item.versionId, versionSelect.value, activeModProfile.id) : await window.icecream.installMod(item.id, versionSelect.value, activeModProfile.id))); for (const item of projects) { installedProjectIds.add(item.id); reflectInstalled(item.id); } modStatus.textContent = `Installed ${[...new Set(installed.map(item => item.name))].join(', ')} into ${activeModProfile.name}.`; button.textContent = 'Installed'; } catch (error) { button.disabled = false; button.textContent = original; modStatus.textContent = `Install failed: ${error.message}`; } }
function renderMods(mods, container, isSearch = false) {
  clear(container); if (!mods.length) { const empty = document.createElement('p'); empty.className = 'mod-empty'; empty.textContent = 'No mods found for this version.'; container.append(empty); return; }
  for (const mod of mods) { const card = document.createElement('article'); card.className = 'mod-card'; const icon = document.createElement('img'); icon.className = 'mod-icon'; icon.alt = ''; icon.referrerPolicy = 'no-referrer'; if (mod.icon) icon.src = mod.icon; const information = document.createElement('div'); const title = document.createElement('div'); title.className = 'mod-title'; title.textContent = mod.title; if (isSearch && recommendedProjectIds.has(mod.id)) { const badge = document.createElement('span'); badge.className = 'recommended-badge'; badge.textContent = 'Recommended'; title.append(' ', badge); } const description = document.createElement('div'); description.className = 'mod-description'; description.textContent = mod.description || ''; const meta = document.createElement('div'); meta.className = 'mod-meta'; meta.textContent = `${formatDownloads(mod.downloads)} downloads`; information.append(title, description, meta); const install = document.createElement('button'); install.className = 'mod-install'; install.dataset.projectId = mod.id; install.textContent = installedProjectIds.has(mod.id) ? 'Installed' : 'Install'; install.addEventListener('click', () => installProjects([mod], install, 'Installing…')); card.append(icon, information, install); container.append(card); }
}
function renderFeatured(groups) { clear(featuredSections); recommendedProjects = []; recommendedProjectIds = new Set(); for (const group of groups) { const section = document.createElement('section'); section.className = 'featured-section'; const title = document.createElement('h3'); title.textContent = group.title; const description = document.createElement('p'); description.className = 'section-description'; description.textContent = group.description; const list = document.createElement('div'); list.className = 'mod-results'; renderMods(group.mods, list); section.append(title, description, list); featuredSections.append(section); recommendedProjects.push(...group.mods); group.mods.forEach(mod => recommendedProjectIds.add(mod.id)); } installFpsPack.disabled = !recommendedProjects.length; }
async function searchMods(query) { modStatus.textContent = 'Searching…'; recommendations.hidden = true; searchSection.hidden = false; clear(modResults); try { const mods = await window.icecream.searchMods(query, versionSelect.value); renderMods(mods, modResults, true); modStatus.textContent = `${mods.length} mod${mods.length === 1 ? '' : 's'} found.`; } catch (error) { modStatus.textContent = `Search failed: ${friendlyError(error)}`; } }
function renderEditorMods(mods, container, installedIds) {
  clear(container); if (!mods.length) { const empty = document.createElement('p'); empty.className = 'mod-empty'; empty.textContent = 'No mods found for this version.'; container.append(empty); return; }
  for (const mod of mods) { const card = document.createElement('article'); card.className = 'mod-card'; const icon = document.createElement('img'); icon.className = 'mod-icon'; icon.alt = ''; icon.referrerPolicy = 'no-referrer'; if (mod.icon) icon.src = mod.icon; const info = document.createElement('div'); const title = document.createElement('div'); title.className = 'mod-title'; title.textContent = mod.title; const description = document.createElement('div'); description.className = 'mod-description'; description.textContent = mod.description || ''; const meta = document.createElement('div'); meta.className = 'mod-meta'; meta.textContent = `${formatDownloads(mod.downloads)} downloads`; info.append(title, description, meta); const button = document.createElement('button'); button.className = 'mod-install'; button.textContent = installedIds.has(mod.id) ? 'Installed' : 'Add'; button.disabled = installedIds.has(mod.id); button.addEventListener('click', async () => { button.disabled = true; button.textContent = 'Adding…'; try { await window.icecream.installMod(mod.id, editingProfile.gameVersion, editingProfile.id); await loadProfileEditor(); notify(`${mod.title} added.`, 'success'); } catch (error) { button.disabled = false; button.textContent = 'Add'; editorStatus.textContent = `Could not add mod: ${friendlyError(error)}`; } }); card.append(icon, info, button); container.append(card); }
}
async function loadProfileEditor() {
  if (!editingProfile) { showView('profiles'); return; }
  const profiles = await window.icecream.modProfiles(); editingProfile = profiles.find(item => item.id === editingProfile.id) || null;
  if (!editingProfile) { showView('profiles'); return; }
  editorName.textContent = editingProfile.name; editorMeta.textContent = `${editingProfile.gameVersion} • ${editingProfile.autoSync ? 'Auto-update on' : 'Auto-update off'}`; editorVersion.textContent = editingProfile.gameVersion; editorAutosync.checked = editingProfile.autoSync === true; editorInstalledStatus.textContent = 'Loading mods…'; editorStatus.textContent = 'Loading recommendations…';
  try {
    const [installed, groups] = await Promise.all([window.icecream.installedMods(editingProfile.gameVersion, editingProfile.id), window.icecream.featuredMods(editingProfile.gameVersion)]); const ids = new Set(installed.map(mod => mod.projectId)); clear(editorInstalled);
    if (!installed.length) editorInstalled.innerHTML = '<p class="mod-empty">No mods yet. Add a recommendation or search on the right.</p>';
    else {
      const projects = await Promise.all(installed.map(async mod => { try { return await window.icecream.modProject(mod.projectId); } catch { return null; } }));
      for (const [index, mod] of installed.entries()) {
      const card = document.createElement('article'); card.className = 'mod-card installed-profile-mod'; const icon = document.createElement('img'); icon.className = 'mod-icon'; icon.alt = ''; icon.src = 'assets/swirl-logo.svg'; icon.addEventListener('error', () => { icon.src = 'assets/swirl-logo.svg'; }, { once: true });
      const project = projects[index]; if (project?.icon_url) icon.src = project.icon_url;
      const info = document.createElement('div'); const title = document.createElement('div'); title.className = 'mod-title'; title.textContent = project?.title || mod.name; const meta = document.createElement('div'); meta.className = 'mod-meta'; meta.textContent = mod.versionNumber || mod.versionId; info.append(title, meta);
      const remove = document.createElement('button'); remove.className = 'danger-action compact-danger'; remove.textContent = 'Remove'; remove.addEventListener('click', async () => { if (!window.confirm(`Remove ${title.textContent} from ${editingProfile.name}? Swirl will create a backup first.`)) return; remove.disabled = true; try { await window.icecream.removeMod(mod.projectId, editingProfile.gameVersion, editingProfile.id); notify(`${title.textContent} removed.`, 'success'); await loadProfileEditor(); } catch (error) { editorStatus.textContent = friendlyError(error); remove.disabled = false; } });
      card.append(icon, info, remove); editorInstalled.append(card);
      }
    }
    editorInstalledStatus.textContent = `${installed.length} installed mod${installed.length === 1 ? '' : 's'}.`; renderEditorMods(groups.flatMap(group => group.mods).slice(0, 12), editorRecommended, ids); editorRecommended.hidden = false; editorResults.hidden = true; editorStatus.textContent = 'Recommended for this version.';
  } catch (error) { editorStatus.textContent = `Could not load the profile editor: ${friendlyError(error)}`; }
}
async function searchEditorMods(query) { if (!editingProfile) return; if (!query) { editorResults.hidden = true; editorRecommended.hidden = false; editorStatus.textContent = 'Showing compatible recommendations.'; return; } editorStatus.textContent = `Searching Fabric ${editingProfile.gameVersion} mods…`; try { const [mods, installed] = await Promise.all([window.icecream.searchMods(query, editingProfile.gameVersion), window.icecream.installedMods(editingProfile.gameVersion, editingProfile.id)]); editorRecommended.hidden = true; editorResults.hidden = false; renderEditorMods(mods, editorResults, new Set(installed.map(mod => mod.projectId))); editorStatus.textContent = `${mods.length} compatible result${mods.length === 1 ? '' : 's'} for ${editingProfile.name}.`; } catch (error) { editorStatus.textContent = `Search failed: ${friendlyError(error)}`; } }

function profileMatches(profileData) { const term = profileSearch.value.trim().toLowerCase(); return (!term || profileData.name.toLowerCase().includes(term) || profileData.gameVersion.includes(term)) && (profileFilter !== 'current' || profileData.gameVersion === versionSelect.value) && (profileFilter !== 'sync' || profileData.autoSync === true); }
async function useProfile(profileData) { versionSelect.value = profileData.gameVersion; loadVersionPicker(); activeProfileInput.value = profileData.id; await loadActiveProfilePicker(); await persistActiveProfile(); await window.icecream.saveSettings({ lastVersion: profileData.gameVersion }); await refreshLibraryForVersion(); showView('library'); }
async function copyProfileCode(profileData, button) { const code = await window.icecream.exportModProfile(profileData.id); try { await navigator.clipboard.writeText(code); button.textContent = 'Copied'; setTimeout(() => { button.textContent = 'Share'; }, 1300); } catch { const area = document.createElement('textarea'); area.className = 'profile-code'; area.readOnly = true; area.value = code; button.closest('.profile-card').append(area); button.textContent = 'Code shown'; } }
async function loadProfiles() {
  profilesStatus.textContent = 'Loading profiles…'; clear(profilesList);
  try {
    const profiles = await window.icecream.modProfiles(); const visible = profiles.filter(profileMatches);
    profileCount.textContent = `${visible.length} profile${visible.length === 1 ? '' : 's'}`;
    profilesStatus.textContent = profiles.length ? 'Each profile has its own worlds, mods, and settings.' : 'Create your first profile above.';
    if (!visible.length) { const empty = document.createElement('p'); empty.className = 'mod-empty'; empty.textContent = profiles.length ? 'No profiles match.' : 'No profiles yet.'; profilesList.append(empty); return; }
    for (const profileData of visible) {
      const card = document.createElement('article'); card.className = 'profile-card'; card.tabIndex = 0; card.setAttribute('aria-label', `Edit ${profileData.name}`);
      const cover = document.createElement('div'); cover.className = 'profile-cover'; const logo = document.createElement('img'); logo.src = 'assets/swirl-logo.svg'; logo.alt = ''; const version = document.createElement('span'); version.className = 'profile-version'; version.textContent = profileData.gameVersion; cover.append(logo, version);
      const title = document.createElement('strong'); title.textContent = profileData.name; const meta = document.createElement('span'); meta.className = 'mod-meta'; meta.textContent = `${profileData.mods.length} mod${profileData.mods.length === 1 ? '' : 's'} • auto-update ${profileData.autoSync ? 'on' : 'off'}`;
      const syncRow = document.createElement('label'); syncRow.className = 'profile-sync'; const sync = document.createElement('input'); sync.type = 'checkbox'; sync.checked = profileData.autoSync === true; const syncText = document.createElement('span'); syncText.textContent = 'Auto-update'; sync.addEventListener('change', async () => { await window.icecream.saveModProfile(profileData.id, { autoSync: sync.checked }); await loadActiveProfilePicker(); await loadProfiles(); }); syncRow.append(sync, syncText);
      const actions = document.createElement('div'); actions.className = 'profile-card-actions'; const play = document.createElement('button'); play.className = 'mod-install'; play.textContent = profileData.id === activeModProfile?.id ? 'Selected' : 'Use'; play.disabled = profileData.id === activeModProfile?.id; play.addEventListener('click', () => useProfile(profileData)); const edit = document.createElement('button'); edit.className = 'secondary-action'; edit.textContent = 'Edit'; edit.addEventListener('click', () => { editingProfile = profileData; showView('editor'); }); const share = document.createElement('button'); share.className = 'icon-button'; share.title = 'Copy profile code'; share.setAttribute('aria-label', `Share ${profileData.name}`); share.textContent = '↗'; share.addEventListener('click', () => copyProfileCode(profileData, share)); actions.append(play, edit, share);
      card.append(cover, title, meta, syncRow, actions); profilesList.append(card);
    }
  } catch (error) { profilesStatus.textContent = `Could not load profiles: ${friendlyError(error)}`; }
}
async function loadSettings() { const configuredVersion = settingsVersion.value || versionSelect.value || '26.2'; settingsStatus.textContent = 'Loading versions…'; try { const settings = await window.icecream.settings(); autoUpdate.checked = settings.autoUpdate; beginnerMode.checked = settings.beginnerMode !== false; experimentalVersions.checked = settings.experimentalVersions === true; reducedMotion.checked = settings.reducedMotion === true; readableFont.checked = settings.readableFont === true; uiScale.value = String(settings.uiScale || 1); backupRetention.value = String(settings.backupRetention || 5); applyAccessibility(settings); createCustomPicker(settingsVersionPicker, settingsVersion, versionOptions(), configuredVersion); const loaders = await window.icecream.fabricLoaders(settingsVersion.value); const options = loaders.map(loader => ({ value: loader.version, label: `${loader.version}${loader.stable ? ' - recommended' : ''}` })); createCustomPicker(fabricLoaderPicker, fabricLoader, options, settings.fabricLoaderVersions?.[settingsVersion.value] || settings.fabricLoaderVersion || loaders.find(loader => loader.stable)?.version); settingsStatus.textContent = `Settings for ${settingsVersion.value}.`; } catch (error) { settingsStatus.textContent = `Could not load settings: ${friendlyError(error)}`; } }
async function refreshLibraryForVersion() { activeVersionBadge.textContent = `Fabric • ${versionSelect.value}`; libraryVersion.textContent = `Fabric • ${versionSelect.value}`; await refreshInstalledIndex(); }

window.icecream.onProgress(event => { progressWrap.hidden = false; const loadingAssets = event.stage === 'assets' || (event.stage === 'download' && String(event.message).startsWith('Asset ')); const message = loadingAssets ? 'Loading assets…' : event.message; progressLabel.textContent = message; if (event.stage === 'metadata') setProgressTarget(4); else if (event.stage === 'download' && !loadingAssets) setProgressTarget(Math.min(34, targetProgress + (event.percent >= 100 ? 0.7 : 0.05))); else if (event.stage === 'assets') setProgressTarget(35 + event.percent * 0.65); else if (event.stage === 'launch') setProgressTarget(100); setStatus(message); });
document.querySelectorAll('[data-window]').forEach(button => button.addEventListener('click', () => window.icecream.windowControl(button.dataset.window)));
document.addEventListener('click', event => { if (!event.target.closest('.custom-picker')) document.querySelectorAll('.custom-picker.open').forEach(picker => { picker.classList.remove('open'); const list = picker.querySelector('.picker-list'); const trigger = picker.querySelector('.picker-trigger'); if (list) list.hidden = true; if (trigger) trigger.setAttribute('aria-expanded', 'false'); }); });
document.querySelectorAll('[data-back]').forEach(button => button.addEventListener('click', () => showView('library')));
openLibrary.addEventListener('click', () => showView('library')); homeBrand.addEventListener('click', () => showView('library')); heroProfiles.addEventListener('click', () => showView('profiles')); heroMods.addEventListener('click', () => { if (activeModProfile) { editingProfile = activeModProfile; showView('editor'); } else showView('profiles'); }); quickNewProfile.addEventListener('click', () => { showView('profiles'); setTimeout(() => profileNameInput.focus(), 0); }); openProfiles.addEventListener('click', () => showView('profiles')); openSettings.addEventListener('click', () => showView('settings'));
clearSearch.addEventListener('click', () => { modQuery.value = ''; searchSection.hidden = true; recommendations.hidden = false; }); openImport.addEventListener('click', () => { importArea.hidden = !importArea.hidden; if (!importArea.hidden) importProfileCode.focus(); }); focusNewProfile.addEventListener('click', () => profileNameInput.focus()); profileSearch.addEventListener('input', loadProfiles); document.querySelectorAll('[data-profile-filter]').forEach(button => button.addEventListener('click', () => { profileFilter = button.dataset.profileFilter; document.querySelectorAll('[data-profile-filter]').forEach(item => item.classList.toggle('selected', item === button)); loadProfiles(); }));
profilesList.addEventListener('keydown', event => { if ((event.key === 'Enter' || event.key === ' ') && event.target.classList.contains('profile-card')) { event.preventDefault(); event.target.click(); } });
profilesList.addEventListener('click', async event => { const card = event.target.closest('.profile-card'); if (!card || event.target.closest('button,input,textarea,label')) return; const visible = (await window.icecream.modProfiles()).filter(profileMatches); editingProfile = visible[[...profilesList.children].indexOf(card)] || null; if (editingProfile) showView('editor'); });
editorView.querySelector('.back').addEventListener('click', () => showView('profiles')); editorSearch.addEventListener('submit', event => { event.preventDefault(); searchEditorMods(editorQuery.value.trim()); }); editorPlay.addEventListener('click', async () => { if (!editingProfile) return; await useProfile(editingProfile); launchButton.click(); });
editorUpdate.addEventListener('click', async () => { if (!editingProfile) return; editorUpdate.disabled = true; editorUpdate.setAttribute('aria-busy', 'true'); const oldLabel = editorUpdate.textContent; editorUpdate.textContent = 'Checking…'; try { const updates = await window.icecream.updateMods(editingProfile.gameVersion, editingProfile.id); await loadProfileEditor(); const message = updates.length ? `${updates.length} mod update${updates.length === 1 ? '' : 's'} installed.` : 'Everything is up to date.'; editorStatus.textContent = message; notify(message, 'success'); } catch (error) { editorStatus.textContent = `Update failed: ${friendlyError(error)}`; } finally { editorUpdate.disabled = false; editorUpdate.removeAttribute('aria-busy'); editorUpdate.textContent = oldLabel; } });
editorAutosync.addEventListener('change', async () => { if (!editingProfile) return; editorAutosync.disabled = true; try { editingProfile = await window.icecream.saveModProfile(editingProfile.id, { autoSync: editorAutosync.checked }); editorMeta.textContent = `Minecraft ${editingProfile.gameVersion} • ${editingProfile.autoSync ? 'Auto-update before launch' : 'Manual mod updates'}`; await loadActiveProfilePicker(); notify(editingProfile.autoSync ? 'Automatic mod updates enabled.' : 'Automatic mod updates disabled.', 'success'); } catch (error) { editorAutosync.checked = !editorAutosync.checked; editorStatus.textContent = friendlyError(error); } finally { editorAutosync.disabled = false; } });
$('editor-rename').addEventListener('click', async () => { if (!editingProfile) return; const name = window.prompt('New profile name', editingProfile.name); if (!name?.trim()) return; try { editingProfile = await window.icecream.saveModProfile(editingProfile.id, { name }); await loadProfileEditor(); notify('Profile renamed.', 'success'); } catch (error) { editorStatus.textContent = friendlyError(error); } });
$('editor-duplicate').addEventListener('click', async () => { if (!editingProfile) return; try { const copy = await window.icecream.duplicateModProfile(editingProfile.id, `${editingProfile.name} Copy`); notify(`${copy.name} created.`, 'success'); await loadProfileSourcePicker(); await loadProfiles(); } catch (error) { editorStatus.textContent = friendlyError(error); } });
$('backup-dialog-close').addEventListener('click', () => $('backup-dialog').close());
window.swirlOpenBackups = async ({ kind, id, title, onRestore }) => { const dialog = $('backup-dialog'); const list = $('backup-dialog-list'); const feedback = $('backup-dialog-status'); $('backup-dialog-title').textContent = `${title} backups`; clear(list); feedback.textContent = 'Loading backups…'; if (!dialog.open) dialog.showModal(); const load = async () => { try { const backups = kind === 'server' ? await window.icecream.serverBackups(id) : await window.icecream.profileBackups(id); clear(list); feedback.textContent = backups.length ? `${backups.length} backup${backups.length === 1 ? '' : 's'} available.` : 'No backups yet.'; for (const backup of backups) { const card = document.createElement('article'); card.className = 'backup-card'; const info = document.createElement('div'); const name = document.createElement('strong'); name.textContent = new Date(backup.modifiedAt || backup.createdAt).toLocaleString(); const meta = document.createElement('small'); meta.textContent = `${formatBytes(backup.size)} • ${backup.id}`; info.append(name, meta); const restore = document.createElement('button'); restore.className = 'mod-install'; restore.textContent = 'Restore'; restore.addEventListener('click', async () => { if (!window.confirm(`Restore the backup from ${name.textContent}? Current files will be kept in Swirl Trash.`)) return; restore.disabled = true; try { if (kind === 'server') await window.icecream.restoreServerBackup(id, backup.id); else await window.icecream.restoreProfileBackup(id, backup.id); feedback.textContent = 'Backup restored.'; notify(`${title} restored.`, 'success'); await onRestore?.(); dialog.close(); } catch (error) { feedback.textContent = friendlyError(error); restore.disabled = false; } }); const remove = document.createElement('button'); remove.className = 'danger-action'; remove.textContent = 'Delete backup'; remove.addEventListener('click', async () => { if (!window.confirm('Permanently delete this backup?')) return; try { if (kind === 'server') await window.icecream.deleteServerBackup(id, backup.id); else await window.icecream.deleteProfileBackup(id, backup.id); await load(); } catch (error) { feedback.textContent = friendlyError(error); } }); card.append(info, restore, remove); list.append(card); } } catch (error) { feedback.textContent = friendlyError(error); } }; await load(); };
$('editor-backup').addEventListener('click', async () => { if (!editingProfile) return; try { const result = await window.icecream.backupModProfile(editingProfile.id); editorStatus.textContent = `Backup saved: ${result.createdAt}`; notify('Profile backed up.', 'success'); } catch (error) { editorStatus.textContent = friendlyError(error); } });
$('editor-restore').addEventListener('click', async () => { if (!editingProfile) return; await window.swirlOpenBackups({ kind: 'profile', id: editingProfile.id, title: editingProfile.name, onRestore: loadProfileEditor }); });
$('editor-repair').addEventListener('click', async () => { if (!editingProfile) return; try { const result = await window.icecream.repairModProfile(editingProfile.id); editorStatus.textContent = `Repair complete. ${result.mods} mod files verified.`; notify('Profile repaired.', 'success'); } catch (error) { editorStatus.textContent = friendlyError(error); } });
$('editor-sync-settings').addEventListener('click', async () => { if (!editingProfile) return; if (!window.confirm(`Copy Minecraft controls, video, audio, and accessibility settings from ${editingProfile.name} to every other profile? Existing settings are backed up first.`)) return; const button = $('editor-sync-settings'); button.disabled = true; button.setAttribute('aria-busy', 'true'); const label = button.textContent; button.textContent = 'Syncingâ€¦'; try { const result = await window.icecream.syncProfileSettings(editingProfile.id); const message = result.synced.length ? `Settings synced to ${result.synced.length} profile${result.synced.length === 1 ? '' : 's'}.${result.skipped.length ? ` ${result.skipped.length} skipped.` : ''}` : 'There are no other profiles to sync.'; editorStatus.textContent = message; notify(message, result.skipped.length ? 'warning' : 'success'); } catch (error) { editorStatus.textContent = friendlyError(error); } finally { button.disabled = false; button.removeAttribute('aria-busy'); button.textContent = label; } });
$('editor-folder').addEventListener('click', async () => { if (!editingProfile) return; try { await window.icecream.openProfileFolder(editingProfile.id); } catch (error) { editorStatus.textContent = friendlyError(error); } });
$('editor-delete').addEventListener('click', async () => { if (!editingProfile || !window.confirm(`Delete ${editingProfile.name}? It will be moved to Swirl Trash so it can be recovered manually.`)) return; try { const deletedId = editingProfile.id; const removed = await window.icecream.deleteModProfile(deletedId); editingProfile = null; if (activeModProfile?.id === deletedId) activeModProfile = null; await loadActiveProfilePicker(); showView('profiles'); notify(`${removed.name} moved to Trash.`, 'success'); } catch (error) { editorStatus.textContent = friendlyError(error); } });
minecraftVersionPicker.addEventListener('icecream-change', async () => { activeProfileInput.value = ''; await window.icecream.saveSettings({ lastVersion: versionSelect.value }); await loadActiveProfilePicker(); await refreshLibraryForVersion(); }); activeProfilePicker.addEventListener('icecream-change', async () => { const profiles = await window.icecream.modProfiles(); activeModProfile = profiles.find(item => item.id === activeProfileInput.value) || null; await persistActiveProfile(); await refreshInstalledIndex(); });
settingsVersionPicker.addEventListener('icecream-change', loadSettings);
createProfile.addEventListener('submit', async event => { event.preventDefault(); try { profilesStatus.textContent = 'Creating profile…'; const created = await window.icecream.createModProfile(profileNameInput.value, profileCreateVersion.value || versionSelect.value, profileSourceInput.value); profileNameInput.value = ''; await useProfile(created); await loadProfileSourcePicker(); await loadProfiles(); const skipped = created.lastMigration?.skipped || []; if (skipped.length) { profilesStatus.textContent = `${created.name} created. ${skipped.length} incompatible mod${skipped.length === 1 ? '' : 's'} skipped: ${skipped.map(item => item.name).join(', ')}.`; notify('Profile created with incompatible mods skipped.', 'warning'); } else notify(`${created.name} created.`, 'success'); } catch (error) { profilesStatus.textContent = `Could not create profile: ${friendlyError(error)}`; } });
importProfile.addEventListener('click', async () => { importProfile.disabled = true; profilesStatus.textContent = 'Installing profile mods...'; try { const imported = await window.icecream.importModProfile(importProfileCode.value); importProfileCode.value = ''; await useProfile(imported); await loadProfileSourcePicker(); await loadProfiles(); notify('Shared profile imported.', 'success'); } catch (error) { profilesStatus.textContent = `Import failed: ${friendlyError(error)}`; } finally { importProfile.disabled = false; } });
modSearch.addEventListener('submit', event => { event.preventDefault(); searchMods(modQuery.value.trim()); }); installFpsPack.addEventListener('click', () => installProjects(recommendedProjects, installFpsPack, 'Installing...'));
saveSettings.addEventListener('click', async () => { const settings = await window.icecream.settings(); const experimentalChanged = settings.experimentalVersions !== experimentalVersions.checked; const saved = await window.icecream.saveSettings({ autoUpdate: autoUpdate.checked, beginnerMode: beginnerMode.checked, experimentalVersions: experimentalVersions.checked, reducedMotion: reducedMotion.checked, readableFont: readableFont.checked, uiScale: Number(uiScale.value), backupRetention: Number(backupRetention.value), fabricLoaderVersions: { ...(settings.fabricLoaderVersions || {}), [settingsVersion.value]: fabricLoader.value } }); applyAccessibility(saved); if (experimentalChanged) { supportedVersions = await window.icecream.fetchVersions(); if (!supportedVersions.some(item => item.id === versionSelect.value)) versionSelect.value = supportedVersions[0]?.id || '26.2'; loadVersionPicker(); loadProfileCreationVersionPicker(); } settingsStatus.textContent = `Settings saved for Minecraft ${settingsVersion.value}.`; notify('Settings saved.', 'success'); });
$('copy-diagnostics').addEventListener('click', async () => { try { const report = JSON.stringify(await window.icecream.diagnostics(), null, 2); await navigator.clipboard.writeText(report); notify('Troubleshooting info copied.', 'success'); } catch (error) { settingsStatus.textContent = friendlyError(error); } });
$('check-launcher-update').addEventListener('click', async () => { const button = $('check-launcher-update'); const feedback = $('launcher-update-status'); button.disabled = true; feedback.textContent = 'Checking signed release information…'; try { const result = await window.icecream.checkLauncherUpdate(); if (!result.enabled) feedback.textContent = result.message; else if (!result.available) feedback.textContent = `Swirl ${result.currentVersion} is up to date.`; else { feedback.textContent = `Swirl ${result.payload.version} is available. ${result.payload.notes || ''}`; $('install-launcher-update').hidden = false; } } catch (error) { feedback.textContent = friendlyError(error); } finally { button.disabled = false; } });
$('install-launcher-update').addEventListener('click', async () => { const button = $('install-launcher-update'); const feedback = $('launcher-update-status'); if (!window.confirm('Download and install this signed Swirl update? The launcher will restart.')) return; button.disabled = true; feedback.textContent = 'Downloading and verifying update…'; try { const result = await window.icecream.stageLauncherUpdate(); if (!result.available) { feedback.textContent = 'Swirl is already up to date.'; button.hidden = true; return; } feedback.textContent = 'Installing update…'; await window.icecream.applyLauncherUpdate(); } catch (error) { feedback.textContent = friendlyError(error); button.disabled = false; } });
launchButton.addEventListener('click', async () => { if (!profile) { setStatus('Choose your player name in the top-right corner.'); $('identity-trigger').click(); return; } if (!activeModProfile) { setStatus('Choose or create a profile first.'); showView('profiles'); return; } try { setBusy(true, 'Checking…'); displayedProgress = 0; targetProgress = 0; progressWrap.hidden = false; progressBar.style.width = '0%'; progressPercent.textContent = '0%'; const compatibility = await window.icecream.checkModCompatibility(versionSelect.value, activeModProfile.id); if (compatibility.errors.length) throw new Error(compatibility.errors.join(' ')); if (compatibility.warnings.length && !window.confirm(`Swirl found something it could not fully check:\n\n${compatibility.warnings.join('\n')}\n\nPlay anyway?`)) { setStatus('Play cancelled.'); setBusy(false, 'Play'); return; } await window.icecream.launchGame(profile, versionSelect.value, activeModProfile); setProgressTarget(100); setStatus('Minecraft started.'); setBusy(false, 'Play'); } catch (error) { setStatus(`Could not start: ${friendlyError(error)}`); setBusy(false, 'Try again'); } });
async function runWelcome() { const welcome = $('welcome'); $('welcome-name').value = profile?.username || `Swirl${Math.floor(1000 + Math.random() * 9000)}`; welcome.hidden = false; $('welcome-later').onclick = () => { localStorage.setItem('swirl-onboarding-complete', 'true'); welcome.hidden = true; }; $('welcome-start').onclick = async () => { const button = $('welcome-start'); button.disabled = true; $('welcome-status').textContent = 'Creating profile…'; try { profile = await window.icecream.offlinePlayer($('welcome-name').value); localStorage.setItem('swirl-player-name', profile.username); updateProfile(profile); const created = await window.icecream.createModProfile($('welcome-profile').value, versionSelect.value, ''); await useProfile(created); if ($('welcome-performance').checked) { $('welcome-status').textContent = 'Adding performance mods…'; const groups = await window.icecream.featuredMods(created.gameVersion); for (const mod of groups.flatMap(group => group.mods)) await window.icecream.installMod(mod.id, created.gameVersion, created.id); } localStorage.setItem('swirl-onboarding-complete', 'true'); welcome.hidden = true; notify('Ready to play.', 'success'); } catch (error) { $('welcome-status').textContent = friendlyError(error); button.disabled = false; } }; }
async function initialize() { setActiveTab('library'); try { const savedTestName = localStorage.getItem('swirl-player-name') || localStorage.getItem('icecream-test-name') || `Swirl${Math.floor(1000 + Math.random() * 9000)}`; localStorage.setItem('swirl-player-name', savedTestName); updateProfile(await window.icecream.offlinePlayer(savedTestName)); const [versions, settings, profiles] = await Promise.all([window.icecream.fetchVersions(), window.icecream.settings(), window.icecream.modProfiles()]); applyAccessibility(settings); supportedVersions = versions; versionSelect.value = versions.some(item => item.id === settings.lastVersion) ? settings.lastVersion : versions.some(item => item.id === '26.2') ? '26.2' : versions.some(item => item.id === '1.21.1') ? '1.21.1' : versions[0]?.id || '26.2'; loadVersionPicker(); await loadActiveProfilePicker(); await refreshLibraryForVersion(); if (!profiles.length && localStorage.getItem('swirl-onboarding-complete') !== 'true') runWelcome(); else setStatus(activeModProfile ? `${activeModProfile.name} is ready.` : 'Choose or create a profile to play.'); await window.icecream.markLauncherHealthy(); } catch (error) { setStatus(`Startup needs attention: ${friendlyError(error)}`); }
}
window.addEventListener('icecream-identity-change', event => updateProfile(event.detail));
initialize();
